[provider]
astraea_eod         = 'Astraea Earth OnDemand (EOD)'
cop_ads             = 'Copernicus Atmosphere Data Store (ADS)'
cop_cds             = 'Copernicus Climate Data Store (CDS)'
cop_dataspace       = 'Copernicus Data Space Ecosystem (CDSE)'
creodias            = 'Copernicus Earth Observation Data and Information Access Services (CREODIAS)'
earth_search        = 'Earth Engine Data Catalog'
earth_search_cog    = 'Earth Engine Cloud Optimized GeoTIFF (COG)'
earth_search_gcs    = 'Google Cloud Storage (GCS)'
ecmwf               = 'European Centre for Medium-Range Weather Forecasts (ECMWF)'
onda                = 'ONDA DIAS'
peps                = 'Plateforme d’Exploitation des Produits Sentinel (PEPS)'
planetary_computer  = 'Planetary Computer Data Catalog'
sara                = ''
theia               = 'THEIA Data Center'
usgs_satapi_aws     = 'U.S. Geological Survey on AWS'

[product]
CAMS_EAC4           = 'CAMS'
CAMS_GACF_AOT       = 'CAMS Aerosol Optical Thickness'
CAMS_GACF_MR        = 'CAMS'
CAMS_GACF_RH        = 'CAMS'
COP_DEM_GLO30_DGED  = 'Copernicus'
COP_DEM_GLO30_DTED  = 'Copernicus'
COP_DEM_GLO90_DGED  = 'Copernicus'
COP_DEM_GLO90_DTED  = 'Copernicus'
ERA5_SL             = 'ERA5'
L57_REFLECTANCE     = ''
L8_OLI_TIRS_C1L1    = 'LANDSAT-8'
L8_REFLECTANCE      = 'LANDSAT-8'
LANDSAT_C2L1        = 'LANDSAT'
LANDSAT_C2L2        = 'LANDSAT'
LANDSAT_C2L2ALB_BT  = 'LANDSAT'
LANDSAT_C2L2ALB_SR  = 'LANDSAT'
LANDSAT_C2L2ALB_ST  = 'LANDSAT'
LANDSAT_C2L2ALB_TA  = 'LANDSAT'
LANDSAT_C2L2_SR     = 'LANDSAT'
LANDSAT_C2L2_ST     = 'LANDSAT'
MODIS_MCD43A4       = 'MODIS'
NAIP                = 'National Agriculture Imagery Program'
OSO                 = 'Orbiting Solar Observatory'
PLD_BUNDLE          = 'PLEIADES'
PLD_PAN             = 'PLEIADES Panchromatic'
PLD_PANSHARPENED    = 'PLEIADES Pansharpened'
PLD_XS              = 'PLEIADES Multispectral'
S1_SAR_GRD          = 'SENTINEL-1 Ground Range Detected'
S1_SAR_OCN          = 'SENTINEL-1 Ocean product'
S1_SAR_RAW          = 'SENTINEL-1 Raw data'
S1_SAR_SLC          = 'SENTINEL-1 Single Look Complex'
S2_MSI_L1C          = 'SENTINEL-2 Level 1'
S2_MSI_L2A          = 'SENTINEL-2 Level 2'
S2_MSI_L2A_COG      = 'SENTINEL-2 Level 2 coregistered'
S2_MSI_L2A_MAJA     = 'SENTINEL-2 Level 2 with MAJA correction'
S2_MSI_L2B_MAJA_SNOW = 'SENTINEL-2 Level 2 with MAJA snow correction'
S2_MSI_L2B_MAJA_WATER = 'SENTINEL-2 Level 2 with MAJA water correction'
S2_MSI_L3A_WASP     = 'SENTINEL-2 Level 3 with WASP synthetizer'
S3_EFR              = 'SENTINEL-3 Radiance at Full Resolution'
S3_ERR              = 'SENTINEL-3 Radiance at Reduced Resolution'
S3_LAN              = 'SENTINEL-3 Land'
S3_OLCI_L2LFR       = 'SENTINEL-3 OLCI Level 2 Land Full Resolution'
S3_OLCI_L2LRR       = 'SENTINEL-3 OLCI Level 2 Land Reduced Resolution'
S3_OLCI_L2WFR       = 'SENTINEL-3 OLCI Level 2 Water Full Resolution'
S3_OLCI_L2WRR       = 'SENTINEL-3 OLCI Level 2 Water Reduced Resolution'
S3_RAC              = 'SENTINEL-3 Radiometric Calibration'
S3_SLSTR_L1RBT      = 'SENTINEL-3 Level 1 radiances and brightness temperatures'
S3_SLSTR_L2AOD      = 'SENTINEL-3 Level 2 aerosol optical depth'
S3_SLSTR_L2FRP      = 'SENTINEL-3 Level 2 fire radiative power'
S3_SLSTR_L2LST      = 'SENTINEL-3 Level 2 land surface temperature'
S3_SLSTR_L2WST      = 'SENTINEL-3 Level 2 sea surface temperature'
S3_SRA              = 'SENTINEL-3'
S3_SRA_A            = 'SENTINEL-3'
S3_SRA_BS           = 'SENTINEL-3'
S3_SY_AOD           = 'SENTINEL-3 Aerosol Description'
S3_SY_SYN           = 'SENTINEL-3 Surface Reflectance and Aerosol parameters over Land'
S3_SY_V10           = 'SENTINEL-3 Vegetation synthesis over 10 days'
S3_SY_VG1           = 'SENTINEL-3 Vegetation synthesis over 1 day'
S3_SY_VGP           = 'SENTINEL-3 Vegetation reflectance'
S3_WAT              = 'SENTINEL-3 Water'
S5P_L1B_IR_SIR      = 'SENTINEL-5P Level1 Irradiances'
S5P_L1B_IR_UVN      = 'SENTINEL-5P Level1 Irradiances'
S5P_L1B_RA_BD1      = 'SENTINEL-5P Level1 Radiances Band 1'
S5P_L1B_RA_BD2      = 'SENTINEL-5P Level1 Radiances Band 2'
S5P_L1B_RA_BD3      = 'SENTINEL-5P Level1 Radiances Band 3'
S5P_L1B_RA_BD4      = 'SENTINEL-5P Level1 Radiances Band 4'
S5P_L1B_RA_BD5      = 'SENTINEL-5P Level1 Radiances Band 5'
S5P_L1B_RA_BD6      = 'SENTINEL-5P Level1 Radiances Band 6'
S5P_L1B_RA_BD7      = 'SENTINEL-5P Level1 Radiances Band 7'
S5P_L1B_RA_BD8      = 'SENTINEL-5P Level1 Radiances Band 8'
S5P_L2_AER_AI       = 'SENTINEL-5P Level2 Ultraviolet Aerosol Index'
S5P_L2_AER_LH       = 'SENTINEL-5P Level2 Aerosol Layer Height'
S5P_L2_CH4          = 'SENTINEL-5P Level2 Methane'
S5P_L2_CLOUD        = 'SENTINEL-5P Level2 Cloud'
S5P_L2_CO           = 'SENTINEL-5P Level2 Carbon Monoxide'
S5P_L2_HCHO         = 'SENTINEL-5P Level2 Formaldehyde'
S5P_L2_NO2          = 'SENTINEL-5P Level2 Nitrogen Dioxide'
S5P_L2_NP_BD3       = 'SENTINEL-5P Level2 NP Band 3'
S5P_L2_NP_BD6       = 'SENTINEL-5P Level2 NP Band 6'
S5P_L2_NP_BD7       = 'SENTINEL-5P Level2 NP Band 7'
S5P_L2_O3           = 'SENTINEL-5P Level2 Ozone'
S5P_L2_O3_PR        = 'SENTINEL-5P Level2 Ozone Profile'
S5P_L2_O3_TCL       = 'SENTINEL-5P Level2 Tropospheric Ozone'
S5P_L2_SO2          = 'SENTINEL-5P Level2 Sulphur Dioxide'
SPOT5_SPIRIT        = 'SPOT'
SPOT_SWH            = 'SPOT'
SPOT_SWH_OLD        = 'SPOT'
TIGGE_CF_SFC        = ''
VENUS_L1C           = 'Venµs Level 1'
VENUS_L2A_MAJA      = 'Venµs Level 2'
VENUS_L3A_MAJA      = 'Venµs Level 3'